apiVersion : apps/v1
kind: Deployment
metadata:
  name: dremkepipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dremkepipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: dremkepipelinesjavascriptdocker 
    spec:
      containers:
        - name: dremkepipelinesjavascriptdocker 
          image: acrct.azurecr.io/dremkepipelinesjavascriptdocker
          ports:
          - containerPort: 8080
